/*
 * This file is generated by jOOQ.
 */
package com.tej.JooQDemo.jooq.sample.model;


import com.tej.JooQDemo.jooq.sample.model.tables.Author;
import com.tej.JooQDemo.jooq.sample.model.tables.Book;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
