/*
 * This file is generated by jOOQ.
 */
package com.tej.JooQDemo.jooq.sample.model.tables.records;


import com.tej.JooQDemo.jooq.sample.model.tables.Author;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorRecord extends UpdatableRecordImpl<AuthorRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1006349348;

    /**
     * Setter for <code>public.author.author_id</code>.
     */
    public AuthorRecord setAuthorId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.author.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.author.firstname</code>.
     */
    public AuthorRecord setFirstname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.author.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.author.lastname</code>.
     */
    public AuthorRecord setLastname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.author.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Author.AUTHOR.AUTHOR_ID;
    }

    @Override
    public Field<String> field2() {
        return Author.AUTHOR.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return Author.AUTHOR.LASTNAME;
    }

    @Override
    public Integer component1() {
        return getAuthorId();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public Integer value1() {
        return getAuthorId();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public AuthorRecord value1(Integer value) {
        setAuthorId(value);
        return this;
    }

    @Override
    public AuthorRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public AuthorRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public AuthorRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorRecord
     */
    public AuthorRecord() {
        super(Author.AUTHOR);
    }

    /**
     * Create a detached, initialised AuthorRecord
     */
    public AuthorRecord(Integer authorId, String firstname, String lastname) {
        super(Author.AUTHOR);

        set(0, authorId);
        set(1, firstname);
        set(2, lastname);
    }
}
